// Vercel serverless function — saves email to Resend contact list
// and sends the plan to the user's email address.

function sanitizeHtml(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/\bon\w+\s*=\s*["'][^"']*["']/gi, '')
    .replace(/javascript\s*:/gi, '');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed.' });
  }

  const { email, planHtml, planTitle, planSub, language } = req.body || {};

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!email || typeof email !== 'string' || !emailRegex.test(email.trim())) {
    return res.status(400).json({ error: 'Invalid email address.' });
  }

  if (planHtml && typeof planHtml !== 'string') {
    return res.status(400).json({ error: 'Invalid plan content.' });
  }

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    return res.status(500).json({ error: 'Email service not configured.' });
  }

  const isSpanish = language === 'es';
  const safePlanHtml = planHtml ? sanitizeHtml(planHtml) : '';

  // ── 1. Add contact to Resend audience ──────────────────────────────────────
  try {
    await fetch('https://api.resend.com/contacts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${resendKey}`
      },
      body: JSON.stringify({ email: email.trim(), unsubscribed: false })
    });
  } catch (e) {
    console.warn('Could not add contact to Resend audience:', e.message);
  }

  // ── 2. Send the plan email ──────────────────────────────────────────────────
  const subject = isSpanish
    ? 'Tu Plan de Entrenamiento de Golf Personalizado'
    : 'Your Personalized Golf Training Plan';

  const preheader = isSpanish
    ? 'Tu plan de 12 semanas está listo — guárdalo para llevarlo al campo.'
    : 'Your 12-week plan is ready — save it to take to the range.';

  const footerText = isSpanish
    ? 'Generado por Caddova · Construido por Luis Acosta'
    : 'Generated by Caddova · Built by Luis Acosta';

  const unsubText = isSpanish
    ? 'Recibiste este email porque solicitaste guardar tu plan de entrenamiento.'
    : 'You received this email because you requested to save your training plan.';

  const emailHtml = `<!DOCTYPE html>
<html lang="${isSpanish ? 'es' : 'en'}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${subject}</title>
<style>
  body { margin: 0; padding: 0; background: #f0f0ed; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  .wrapper { max-width: 640px; margin: 2rem auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
  .header { background: linear-gradient(135deg, #053D31 0%, #0F6E56 100%); padding: 2rem 2rem 1.5rem; text-align: center; }
  .header h1 { color: #ffffff; font-size: 22px; font-weight: 500; margin: 0 0 4px; }
  .header p { color: #A7F3D0; font-size: 14px; margin: 0; }
  .body { padding: 2rem; }
  .plan-content { font-size: 14px; color: #1a1a1a; line-height: 1.7; }
  .plan-content h1 { font-size: 20px; font-weight: 600; color: #0F6E56; margin: 0 0 0.5rem; }
  .plan-content h2 { font-size: 17px; font-weight: 600; color: #0F6E56; margin: 1.5rem 0 0.4rem; padding-bottom: 0.3rem; border-bottom: 1px solid #e0e0e0; }
  .plan-content h3 { font-size: 15px; font-weight: 600; color: #085041; margin: 1.25rem 0 0.3rem; }
  .plan-content h4 { font-size: 14px; font-weight: 600; color: #085041; margin: 1.25rem 0 0.25rem; }
  .plan-content p { margin: 0 0 0.7rem; }
  .plan-content ul, .plan-content ol { margin: 0.25rem 0 0.75rem 1.5rem; padding: 0; }
  .plan-content li { margin-bottom: 0.3rem; line-height: 1.6; }
  .plan-content strong { color: #1a1a1a; font-weight: 600; }
  .plan-content table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 13px; }
  .plan-content th, .plan-content td { border: 1px solid #e0e0e0; padding: 7px 10px; text-align: left; }
  .plan-content th { background: #f0f0ed; color: #0F6E56; font-weight: 600; }
  .plan-content hr { border: none; border-top: 2px solid #e8e8e4; margin: 2rem 0; }
  .plan-content blockquote { border-left: 3px solid #0F6E56; padding: 0.5rem 0 0.5rem 1rem; margin: 1rem 0; color: #5a5a5a; font-style: italic; background: #f7faf7; border-radius: 0 4px 4px 0; }
  .footer { background: #f7f7f5; padding: 1.25rem 2rem; text-align: center; border-top: 1px solid #e0e0e0; }
  .footer p { font-size: 12px; color: #8a8a8a; margin: 0 0 4px; }
</style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>⛳ ${planTitle || subject}</h1>
      <p>${planSub || preheader}</p>
    </div>
    <div class="body">
      <div class="plan-content">
        ${safePlanHtml || '<p>Your plan content was not included. Please regenerate your plan and try again.</p>'}
      </div>
    </div>
    <div class="footer">
      <p>${footerText}</p>
      <p>${unsubText}</p>
    </div>
  </div>
</body>
</html>`;

  try {
    const sendResp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${resendKey}`
      },
      body: JSON.stringify({
        from: 'Caddova <hello@caddova.com>',
        to: [email.trim()],
        subject: subject,
        html: emailHtml
      })
    });

    const sendData = await sendResp.json();

    if (!sendResp.ok) {
      console.error('Resend send error:', sendData?.name);
      return res.status(502).json({ error: 'Email delivery failed. Please try again.' });
    }

    return res.status(200).json({ success: true, emailSent: true });

  } catch (err) {
    console.error('Save email error:', err.message);
    return res.status(500).json({ error: 'Could not send email. Please try again.' });
  }
}
